config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
      authenticated :user do
        root 'users#current_user_home', as: :authenticated_root
      end

      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end

    root 'suggestions#index'

  resources :suggestions
  devise_for :users
  resources :users, only: [:index, :show]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    #
      # user ||= User.new # guest user (not logged in)
      # if user.current_user?
      #   can :manage, :
      # else
      #   can :read, :all
      # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :user
  mount_uploader :food_image, FoodImageUploader
  geocoded_by :location   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinate  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :suggestions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   mount_uploader :user_image, UserImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def authenticate_user(user)
    if user != current_user
      flash[:error] = "You are not authorized to do that. Please login."
      redirect_to root_path
    else
      true
    end
  end

  protected
    # my custom fields are :username, :user_image
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:username, :user_image, :remote_user_image_url, :email, :password, :password_confirmation)
      end

      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:username, :user_image, :remote_user_image_url, :email, :password, :password_confirmation, :current_password)
      end
    end
  end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: [:show, :edit, :update, :destroy]
  # All Users
  def index
    @suggestions = Suggestion.all
  end

  def show
  end

  def new
    @suggestion = Suggestion.new
  end
# Users can only edit their own suggestions
  def edit
    redirect_to @suggestion unless authenticate_user(@suggestion.user)
  end
  
  def create
    params[:suggestion][:user_id] = current_user.id
    @suggestion = Suggestion.new(suggestion_params)

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully created.' }
        format.json { render :show, status: :created, location: @suggestion }
      else
        format.html { render :new }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @suggestion.update(suggestion_params)
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.html { render :edit }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @suggestion.destroy
    respond_to do |format|
      format.html { redirect_to suggestions_url, notice: 'Suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_suggestion
      @suggestion = Suggestion.find(params[:id])
    end

    # Strong Params
    def suggestion_params
      params.require(:suggestion).permit(:food_image, :remote_food_image_url, :description, :location, :longitude, :lattitude, :category, :food_type, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index 
    @users = User.all
  end

  def current_user_home
    redirect_to current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= favicon_link_tag 'favicon(1).ico' %>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title><%= content_for?(:title) ? yield(:title) : "JustHad" %></title>
  <%= stylesheet_link_tag    "application", media: 'all' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="wrapper">
    <header>
      <nav class="top-bar row" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to "JustHad", root_path %></h1>
          </li>
          <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Suggestions", suggestions_path %></li>
            <% if current_user %>
            <li><%= link_to "New Suggestion", new_suggestion_path %></li>
            <li></li>
            <li class="has-dropdown">
              <a href="#">Account</a>
              <ul class="dropdown">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% else %>
            <li><%= link_to "Register", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
      </section>
    </nav>
  </header>

  <% flash.each do |name, message| %>
  <div data-alert class="alert-box secondary row flash-message flash-message-<%= name %>">
    <%= message %>
    <a href="#" class="close">&times;</a>
  </div>
  <% end %>

  <main class="row">
    <div class="large-12 columns">
      <%= yield %>
    </div>
  </main>
  <div class="push"></div>
</div>
<div class="footer">
  <footer class="footer">
    &copy;2015 Sedky S. Said
  </footer>
</div>

</body>
</html>

app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_image %>
    <%= f.file_field :food_image %>
  </div>
  
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :category %>
    <%= f.select :category, ["Breakfast", "Lunch", "Dinner"] %>
  </div>
  <div class="field">
    <%= f.label :type %>
    <%= f.select :food_type, ["Food", "Drink"] %>
  </div>
  <div class="actions">
    <%= f.submit "Suggest", class: "button expand" %>
  </div>
<% end %>

app/views/suggestions/_suggestion.html.erb
<!-- <div class="box"> -->
<li>
  <ul class='suggestion-tile'>
    <li><%= link_to image_tag(suggestion.food_image.url), suggestion %></li>
    <li><%= suggestion.description %></li>
    <li><%= suggestion.location %></li>
    <li><%= suggestion.user.try(:username) %></li>
    <li><%= suggestion.food_type %></li>
    <li><span class="[success alert secondary] [round radius] label"><%= suggestion.category %></span></li>
  </ul>
</li>
<!-- </div> -->

app/views/suggestions/edit.html.erb
<h1>Editing Suggestion</h1>

<% if can? :update, @suggestions %>
  <%= link_to "Edit", edit_suggestions_path(@suggestions) %>
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<h1>Suggestions</h1>

<ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-3">
<!-- <div id="pins" class="transitions-enabled"> -->
  <%= render @suggestions %>
  <!-- </div> -->
</ul>     

<%= link_to 'New Suggestion', new_suggestion_path %>

app/views/suggestions/new.html.erb
<h1>New Suggestion</h1>

<%= render 'form' %>

<%= link_to 'Back', suggestions_path %>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>

  <%= image_tag @suggestion.food_image.url, class: "suggestion-show-image" %>


<p>
  <strong>Description:</strong>
  <%= @suggestion.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @suggestion.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @suggestion.user.try(:email) %>
</p>

<% if current_user == @suggestion.user %>
<%= link_to 'Edit', edit_suggestion_path(@suggestion) %> |
<%= link_to 'Destroy', @suggestion, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<div class="nearby-suggestions">
<h2>Nearby Suggestions</h2>
<ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-3">
  <%= render @suggestion.nearbys(5) %>
</ul>

<!--   <% @suggestion.nearbys(5).each do |suggestion| %>
    <%= link_to suggestion.location, suggestion %>
  <% end %> -->
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
   <%= f.label :user_image %><br>
   <%= f.file_field :user_image %>
 </div>

app/views/users/_user.html.erb
<li>
  <%= image_tag user.user_image_url %>
  <%= link_to user.username, user %>
</li>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul class="small-block-grid-3 medium-block-grid-6 large-block-grid-8">
  <%= render @users %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.username %> </h1> 

<%= image_tag @user.user_image, class: "user-profile-image" %>
<h2>My Suggestions</h2>
<ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-3 user-show-suggestions">
  <%= render @user.suggestions %>
</ul>